import numpy as np
import matplotlib.pyplot as plt
from typing import List, Tuple
from utils import electric_field


def visualize_electric_field(
    num_charges: int = 3,
    grid_size: int = 11,
    field_range: float = 10.0e-6,
    seed: int = 42,
    # Electron charge
    charge: float = 1.60217663e-19,
) -> None:
    np.random.seed(seed)
    x = np.linspace(-field_range, field_range, grid_size)
    y = np.linspace(-field_range, field_range, grid_size)
    X, Y = np.meshgrid(x, y)

    points = np.stack([X.flatten(), Y.flatten()], axis=1)
    random_points = points[
        np.random.choice(points.shape[0], size=num_charges, replace=False)
    ]

    print("All points:\n", points)
    print("3 random points:\n", random_points)

    charge_values = np.full(num_charges, charge)

    print("Charge values:\n", charge_values)

    Ex = np.zeros(points.shape[0])
    Ey = np.zeros(points.shape[0])

    print("Ex:\n", Ex)
    print("Ey:\n", Ey)

    for pos, q in zip(random_points, charge_values):
        r_vectors = points - pos
        E = np.array([electric_field(q, r) for r in r_vectors])
        Ex += E[:, 0]
        Ey += E[:, 1]

    print("Ex:\n", Ex)
    print("Ey:\n", Ey)

    plt.figure(figsize=(6, 6))
    plt.quiver(X, Y, Ex, Ey, color="r")
    plt.scatter(random_points[:, 0], random_points[:, 1], color="b", s=100)
    plt.title("Electric Field Generated by Random Charges")
    plt.xlabel("x")
    plt.ylabel("y")
    plt.grid(True)
    plt.show()


if __name__ == "__main__":
    visualize_electric_field()
